name: Draft PDF

on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf