name: Draft PDF

on:
  push:
    branches:
      - paper
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
      - name: Checkout paper branch
        uses: actions/checkout@v4
        with:
          ref: paper

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
          if-no-files-found: error